//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1

import (
	unsafe "unsafe"

	example "github.com/3Xpl0it3r/kubecraft/pkg/apis/example"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Bar)(nil), (*example.Bar)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Bar_To_example_Bar(a.(*Bar), b.(*example.Bar), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*example.Bar)(nil), (*Bar)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_example_Bar_To_v1_Bar(a.(*example.Bar), b.(*Bar), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BarList)(nil), (*example.BarList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_BarList_To_example_BarList(a.(*BarList), b.(*example.BarList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*example.BarList)(nil), (*BarList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_example_BarList_To_v1_BarList(a.(*example.BarList), b.(*BarList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BarSpec)(nil), (*example.BarSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_BarSpec_To_example_BarSpec(a.(*BarSpec), b.(*example.BarSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*example.BarSpec)(nil), (*BarSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_example_BarSpec_To_v1_BarSpec(a.(*example.BarSpec), b.(*BarSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BarStatus)(nil), (*example.BarStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_BarStatus_To_example_BarStatus(a.(*BarStatus), b.(*example.BarStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*example.BarStatus)(nil), (*BarStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_example_BarStatus_To_v1_BarStatus(a.(*example.BarStatus), b.(*BarStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Foo)(nil), (*example.Foo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Foo_To_example_Foo(a.(*Foo), b.(*example.Foo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*example.Foo)(nil), (*Foo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_example_Foo_To_v1_Foo(a.(*example.Foo), b.(*Foo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FooList)(nil), (*example.FooList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_FooList_To_example_FooList(a.(*FooList), b.(*example.FooList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*example.FooList)(nil), (*FooList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_example_FooList_To_v1_FooList(a.(*example.FooList), b.(*FooList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FooSpec)(nil), (*example.FooSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_FooSpec_To_example_FooSpec(a.(*FooSpec), b.(*example.FooSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*example.FooSpec)(nil), (*FooSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_example_FooSpec_To_v1_FooSpec(a.(*example.FooSpec), b.(*FooSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FooStatus)(nil), (*example.FooStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_FooStatus_To_example_FooStatus(a.(*FooStatus), b.(*example.FooStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*example.FooStatus)(nil), (*FooStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_example_FooStatus_To_v1_FooStatus(a.(*example.FooStatus), b.(*FooStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1_Bar_To_example_Bar(in *Bar, out *example.Bar, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_BarSpec_To_example_BarSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1_BarStatus_To_example_BarStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_Bar_To_example_Bar is an autogenerated conversion function.
func Convert_v1_Bar_To_example_Bar(in *Bar, out *example.Bar, s conversion.Scope) error {
	return autoConvert_v1_Bar_To_example_Bar(in, out, s)
}

func autoConvert_example_Bar_To_v1_Bar(in *example.Bar, out *Bar, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_example_BarSpec_To_v1_BarSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_example_BarStatus_To_v1_BarStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_example_Bar_To_v1_Bar is an autogenerated conversion function.
func Convert_example_Bar_To_v1_Bar(in *example.Bar, out *Bar, s conversion.Scope) error {
	return autoConvert_example_Bar_To_v1_Bar(in, out, s)
}

func autoConvert_v1_BarList_To_example_BarList(in *BarList, out *example.BarList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]example.Bar)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_BarList_To_example_BarList is an autogenerated conversion function.
func Convert_v1_BarList_To_example_BarList(in *BarList, out *example.BarList, s conversion.Scope) error {
	return autoConvert_v1_BarList_To_example_BarList(in, out, s)
}

func autoConvert_example_BarList_To_v1_BarList(in *example.BarList, out *BarList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Bar)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_example_BarList_To_v1_BarList is an autogenerated conversion function.
func Convert_example_BarList_To_v1_BarList(in *example.BarList, out *BarList, s conversion.Scope) error {
	return autoConvert_example_BarList_To_v1_BarList(in, out, s)
}

func autoConvert_v1_BarSpec_To_example_BarSpec(in *BarSpec, out *example.BarSpec, s conversion.Scope) error {
	return nil
}

// Convert_v1_BarSpec_To_example_BarSpec is an autogenerated conversion function.
func Convert_v1_BarSpec_To_example_BarSpec(in *BarSpec, out *example.BarSpec, s conversion.Scope) error {
	return autoConvert_v1_BarSpec_To_example_BarSpec(in, out, s)
}

func autoConvert_example_BarSpec_To_v1_BarSpec(in *example.BarSpec, out *BarSpec, s conversion.Scope) error {
	return nil
}

// Convert_example_BarSpec_To_v1_BarSpec is an autogenerated conversion function.
func Convert_example_BarSpec_To_v1_BarSpec(in *example.BarSpec, out *BarSpec, s conversion.Scope) error {
	return autoConvert_example_BarSpec_To_v1_BarSpec(in, out, s)
}

func autoConvert_v1_BarStatus_To_example_BarStatus(in *BarStatus, out *example.BarStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1_BarStatus_To_example_BarStatus is an autogenerated conversion function.
func Convert_v1_BarStatus_To_example_BarStatus(in *BarStatus, out *example.BarStatus, s conversion.Scope) error {
	return autoConvert_v1_BarStatus_To_example_BarStatus(in, out, s)
}

func autoConvert_example_BarStatus_To_v1_BarStatus(in *example.BarStatus, out *BarStatus, s conversion.Scope) error {
	return nil
}

// Convert_example_BarStatus_To_v1_BarStatus is an autogenerated conversion function.
func Convert_example_BarStatus_To_v1_BarStatus(in *example.BarStatus, out *BarStatus, s conversion.Scope) error {
	return autoConvert_example_BarStatus_To_v1_BarStatus(in, out, s)
}

func autoConvert_v1_Foo_To_example_Foo(in *Foo, out *example.Foo, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_FooSpec_To_example_FooSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1_FooStatus_To_example_FooStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_Foo_To_example_Foo is an autogenerated conversion function.
func Convert_v1_Foo_To_example_Foo(in *Foo, out *example.Foo, s conversion.Scope) error {
	return autoConvert_v1_Foo_To_example_Foo(in, out, s)
}

func autoConvert_example_Foo_To_v1_Foo(in *example.Foo, out *Foo, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_example_FooSpec_To_v1_FooSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_example_FooStatus_To_v1_FooStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_example_Foo_To_v1_Foo is an autogenerated conversion function.
func Convert_example_Foo_To_v1_Foo(in *example.Foo, out *Foo, s conversion.Scope) error {
	return autoConvert_example_Foo_To_v1_Foo(in, out, s)
}

func autoConvert_v1_FooList_To_example_FooList(in *FooList, out *example.FooList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]example.Foo)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_FooList_To_example_FooList is an autogenerated conversion function.
func Convert_v1_FooList_To_example_FooList(in *FooList, out *example.FooList, s conversion.Scope) error {
	return autoConvert_v1_FooList_To_example_FooList(in, out, s)
}

func autoConvert_example_FooList_To_v1_FooList(in *example.FooList, out *FooList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Foo)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_example_FooList_To_v1_FooList is an autogenerated conversion function.
func Convert_example_FooList_To_v1_FooList(in *example.FooList, out *FooList, s conversion.Scope) error {
	return autoConvert_example_FooList_To_v1_FooList(in, out, s)
}

func autoConvert_v1_FooSpec_To_example_FooSpec(in *FooSpec, out *example.FooSpec, s conversion.Scope) error {
	return nil
}

// Convert_v1_FooSpec_To_example_FooSpec is an autogenerated conversion function.
func Convert_v1_FooSpec_To_example_FooSpec(in *FooSpec, out *example.FooSpec, s conversion.Scope) error {
	return autoConvert_v1_FooSpec_To_example_FooSpec(in, out, s)
}

func autoConvert_example_FooSpec_To_v1_FooSpec(in *example.FooSpec, out *FooSpec, s conversion.Scope) error {
	return nil
}

// Convert_example_FooSpec_To_v1_FooSpec is an autogenerated conversion function.
func Convert_example_FooSpec_To_v1_FooSpec(in *example.FooSpec, out *FooSpec, s conversion.Scope) error {
	return autoConvert_example_FooSpec_To_v1_FooSpec(in, out, s)
}

func autoConvert_v1_FooStatus_To_example_FooStatus(in *FooStatus, out *example.FooStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1_FooStatus_To_example_FooStatus is an autogenerated conversion function.
func Convert_v1_FooStatus_To_example_FooStatus(in *FooStatus, out *example.FooStatus, s conversion.Scope) error {
	return autoConvert_v1_FooStatus_To_example_FooStatus(in, out, s)
}

func autoConvert_example_FooStatus_To_v1_FooStatus(in *example.FooStatus, out *FooStatus, s conversion.Scope) error {
	return nil
}

// Convert_example_FooStatus_To_v1_FooStatus is an autogenerated conversion function.
func Convert_example_FooStatus_To_v1_FooStatus(in *example.FooStatus, out *FooStatus, s conversion.Scope) error {
	return autoConvert_example_FooStatus_To_v1_FooStatus(in, out, s)
}
